trigger:  # will disable CI builds entirely
 - master
pr: none
# - master
# - releases/*

jobs:
- job: WebApp
  displayName: 'Build Web App'
  pool:
    vmImage: 'windows-2019'
  variables:
    BuildConfiguration: release
  
  steps:
  
  - task: UseDotNet@2
    displayName: Install .NET 7 sdk
    inputs:
      packageType: sdk
      version: 7.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/**.csproj'
  
  
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/**.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  
  
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
  
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact (WebApp.zip)'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'